// `quorum init` — initialize the local Quorum state directory (GitHub issue #18).
//
// Creates `~/.quorum/<hash>/` for the current project. The hash is
// `projectHash(cwd)` from `@quorum/store`, which canonicalizes the path so
// Windows junction / casing / separator variants resolve to the same
// directory (issue #53). Writes a `config.json` and a zero-byte
// `INDEX_DB_FILENAME` placeholder that the store's `SqliteIndex` opens and
// initializes on first use (issue #57 — this file used to be named
// `state.db`, which the store never read). Idempotent.

import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

import { INDEX_DB_FILENAME, storageRoot } from "@quorum/store";

export const CLI_VERSION = "0.0.0" as const;

/**
 * Contents written to `<project>/.gitattributes` when the project has no
 * existing file. Normalizes line endings so Windows clones stop emitting
 * CRLF warnings on every `git add` (issue #70).
 */
export const GITATTRIBUTES_CONTENT =
  `# Auto-generated by \`quorum init\`. Edit freely.\n` +
  `# Normalize line endings; let git handle platform differences.\n` +
  `\n` +
  `* text=auto eol=lf\n` +
  `\n` +
  `# Explicit binary types\n` +
  `*.png binary\n` +
  `*.jpg binary\n` +
  `*.jpeg binary\n` +
  `*.gif binary\n` +
  `*.webp binary\n` +
  `*.ico binary\n` +
  `*.pdf binary\n` +
  `*.zip binary\n` +
  `*.tar.gz binary\n`;

export interface InitEnv {
  /** Working directory of the project to initialize. */
  cwd: string;
  /** User home directory (tests swap this for a temp dir). */
  homeDir: string;
  /** ISO timestamp used in `config.json`. Tests may pin this. */
  now: () => string;
}

export function defaultInitEnv(): InitEnv {
  return {
    cwd: process.cwd(),
    homeDir: homedir(),
    now: () => new Date().toISOString(),
  };
}

export interface InitResult {
  /** Absolute path of the created (or existing) per-project state dir. */
  stateDir: string;
  /** Whether the directory already existed before this run. */
  alreadyInitialized: boolean;
}

export interface ProjectConfig {
  project_path: string;
  created_at: string;
  version: string;
}

/**
 * Perform the filesystem side-effects of `quorum init`. Returns metadata
 * about what happened so the caller can print an appropriate message.
 */
export function initProject(env: InitEnv): InitResult {
  const stateDir = storageRoot(env.cwd, env.homeDir);
  const configPath = join(stateDir, "config.json");
  const dbPath = join(stateDir, INDEX_DB_FILENAME);
  const gitattributesPath = join(env.cwd, ".gitattributes");

  const configExists = existsSync(configPath);
  const dbExists = existsSync(dbPath);

  // Drop a `.gitattributes` in the project root if there isn't one already.
  // Orthogonal to the state-dir markers below, so we do it before the
  // already-initialized short-circuit — a user who deletes the file (or
  // clones into a project that never had one) still gets it on re-init
  // (issue #70). Never overwrite an existing file. Skip silently when the
  // cwd doesn't exist on disk (older tests use synthetic paths).
  if (existsSync(env.cwd) && !existsSync(gitattributesPath)) {
    writeFileSync(gitattributesPath, GITATTRIBUTES_CONTENT, "utf8");
  }

  // Only report already-initialized when BOTH markers are present. A missing
  // index.db with an existing config.json means a previous run was
  // interrupted (or the file was manually deleted); repair instead of
  // silently succeeding.
  if (configExists && dbExists) {
    return { stateDir, alreadyInitialized: true };
  }

  mkdirSync(stateDir, { recursive: true });

  if (!configExists) {
    const config: ProjectConfig = {
      project_path: env.cwd,
      created_at: env.now(),
      version: CLI_VERSION,
    };
    writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf8");
  }

  // Zero-byte placeholder at the filename the store opens. `SqliteIndex`'s
  // constructor will treat an empty file as a fresh database and run the
  // schema DDL on first open. `openSync`/`closeSync` avoids writing even a
  // trailing newline.
  if (!dbExists) {
    const fd = openSync(dbPath, "w");
    closeSync(fd);
  }

  return { stateDir, alreadyInitialized: false };
}

export interface RunInitOptions {
  env?: InitEnv;
  log?: (msg: string) => void;
}

/**
 * Top-level entry for the `init` subcommand. Always exits 0 — idempotent
 * re-runs are not considered an error.
 */
export async function runInit(options: RunInitOptions = {}): Promise<0> {
  const env = options.env ?? defaultInitEnv();
   
  const log = options.log ?? ((msg: string) => console.log(msg));

  const result = initProject(env);
  if (result.alreadyInitialized) {
    log(`Quorum is already initialized for ${env.cwd}`);
  } else {
    log(`Initialized Quorum for ${env.cwd} at ${result.stateDir}`);
  }
  return 0;
}
